### ISSUE TITLE
🔧 [CI/CD] 改善: ワークフローの重複実行と最適化

### ISSUE THREAD

**Issue by 24taro** [sotaroNishioka/notebooklm-collector#120]
## 🔧 [CI/CD] 改善: ワークフローの重複実行と最適化

**カテゴリ**: CI/CD
**優先度**: High
**種別**: enhancement

### 概要

GitHub Actions CI/CDワークフローの実行時間短縮とリソース効率化のため、重複実行の排除、並列化の実装、キャッシュ戦略の改善を行う。

### 現状の問題

1. **ワークフローの重複実行**
   - `build.yml`: ビルドのみ実行（PR/pushで実行）
   - `ci.yml`: リント、型チェック、テスト、ビルド実行（PR/pushで実行、Node 18.x/20.xのマトリックス）
   - `deploy.yml`: リント、型チェック、ビルド実行（mainへのpushで実行）
   - 同じトリガーで複数のワークフローが重複してビルドを実行

2. **非効率な実行順序**
   - ci.ymlで全ての処理が順次実行（リント→型チェック→テスト→ビルド）
   - 並列実行可能な処理が逐次実行されている

3. **不要なマトリックステスト**
   - Node.js 18.xと20.xの両方でテスト実行
   - プロジェクトはNode.js 20.xで動作すれば十分

4. **キャッシュの未活用**
   - .nextディレクトリのキャッシュが未実装
   - ビルド成果物の再利用がない

#### 1. ワークフローの統合と整理
- `build.yml`を削除し、ci.ymlに統合
- Node.jsバージョンを20.xのみに統一
- 重複実行を排除

#### 2. ジョブの並列化
- 以下のジョブを並列実行:
  - `lint`: Biomeによるリントチェック
  - `typecheck`: TypeScript型チェック
  - `test-unit`: Vitestによる単体テスト
  - `test-e2e`: Playwrightによる E2Eテスト
- ビルドジョブは上記すべての成功後に実行

#### 3. キャッシュ戦略の実装
- Node modulesキャッシュ（既存）
- .nextディレクトリキャッシュ
- Playwrightブラウザキャッシュ（既存）
- Storybookキャッシュ（既存）

#### 4. デプロイワークフローの最適化
- CI成功時のビルド成果物を再利用
- 重複するリント・型チェックを削除

### 受け入れ条件

1. **ワークフロー統合の完了**
   - [ ] build.ymlが削除されている
   - [ ] ci.ymlで全てのCI処理が実行される
   - [ ] Node.js 20.xのみでテストが実行される

2. **並列実行の実装**
   - [ ] リント、型チェック、テストが並列で実行される
   - [ ] 依存関係が適切に設定されている
   - [ ] ビルドは全テスト成功後に実行される

3. **実行時間の短縮**
   - [ ] CI実行時間が5分以内（目標）
   - [ ] 並列化によりトータル実行時間が40%以上短縮

4. **キャッシュの有効活用**
   - [ ] .nextディレクトリがキャッシュされる
   - [ ] キャッシュヒット率が80%以上

### 変更箇所候補

1. **削除**
   - `.github/workflows/build.yml`

2. **更新**
   - `.github/workflows/ci.yml` - 並列ジョブ構成、キャッシュ追加
   - `.github/workflows/deploy.yml` - ビルド成果物の再利用

### 実装例

```yaml
# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run type-check

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm test

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      # Playwright キャッシュ設定
      - name: Get Playwright version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright/test | sed 's/.*@//' | head -1)
          echo "version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
      - run: npx playwright install --with-deps chromium
      - run: npm run test:e2e

  build:
    needs: [lint, typecheck, test-unit, test-e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      # .next キャッシュ
      - uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .next/
          retention-days: 1
```

### 成功指標

- CI平均実行時間が5分以内
- ビルドの重複実行がゼロ
- キャッシュヒット率80%以上
- 全てのテストが並列実行される
- デプロイ時間が50%短縮

### リスクと対策

1. **並列実行によるリソース制限**
   - 対策: GitHub Actionsの同時実行数制限を考慮した設計

2. **キャッシュの破損**
   - 対策: キャッシュキーの適切な設計とフォールバック

3. **依存関係の競合**
   - 対策: ジョブ間の依存関係を明確に定義

### 効果測定

- 実装前後のCI実行時間を比較
- リソース使用量（Actions利用時間）の削減率を測定
- 開発者の待ち時間削減による生産性向上を評価

---
🤖 **Monitor により自動生成**
**分析日時**: 2025-06-01 13:16:50 UTC
