### ISSUE TITLE
feat: CI/CD環境の整備とGitHub Actions設定

### ISSUE THREAD

**Issue by 24taro** [sotaroNishioka/notebooklm-collector#64]
## 概要

開発効率とコード品質向上のため、包括的なCI/CD環境を構築する。現在GitHub Actionsの設定が不完全で、プルリクエスト時の自動チェック機能が不足している。

### 未実装
- **GitHub Actions設定**: `.github/workflows/`ディレクトリが存在しない
- **自動テスト実行**: プルリクエスト時のテスト自動実行なし
- **自動品質チェック**: lint、型チェック、ビルドの自動実行なし
- **デプロイ設定**: 本番環境への自動デプロイ設定なし

### 既存の課題
- Issue #58でビルドエラーは修正されたが、継続的な品質管理体制が未構築
- 手動でのlint・型チェック実行に依存

#### 必須ワークフロー
```yaml
.github/workflows/
├── ci.yml           # メインCI（lint, typecheck, test）
├── build.yml        # ビルドテスト
└── deploy.yml       # デプロイ（本番環境）
```

#### ci.ymlの要件
- **Node.js環境**: 複数バージョンでのテスト（18.x, 20.x）
- **依存関係インストール**: npm ci
- **品質チェック**: 
  - `npm run lint`
  - `npm run type-check`
  - `npm test`（テスト実装後）
- **実行条件**: プルリクエスト、mainブランチプッシュ時

#### 必須チェック
- ✅ CI通過が必須
- ✅ ブランチの最新化が必須
- ✅ レビュー承認（1名以上）
- ✅ 管理者による強制マージの制限

#### Vercelとの連携
- プレビューデプロイの自動実行
- 本番デプロイの自動化
- 環境変数の適切な設定

#### 失敗時通知
- GitHub issueへの自動コメント
- 失敗原因の詳細ログ表示

#### 成功時レポート
- ビルド時間の計測
- テストカバレッジレポート（将来的に）

### 推奨GitHub Actionsテンプレート
```yaml
name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - run: npm ci
      - run: npm run lint
      - run: npm run type-check
      - run: npm run build
```

### セキュリティ考慮事項
- **Secrets管理**: デプロイキー、APIトークンの適切な管理
- **権限設定**: 最小権限の原則に従った設定
- **依存関係監査**: npm audit自動実行

### 開発効率向上
- 手動チェック作業の自動化
- 早期エラー発見によるデバッグ時間短縮
- プルリクエストの品質向上

### コード品質向上
- 一貫した品質基準の自動適用
- リグレッション防止
- チーム開発での品質統一

### デプロイ安全性
- 本番環境への安全なデプロイ
- ロールバック機能の確保

### Phase 1: 基本CI設定
1. ci.ymlの作成（lint, typecheck, build）
2. プルリクエスト保護設定
3. 基本通知設定

### Phase 2: 拡張機能
1. テスト自動実行（Issue #52テスト環境構築後）
2. カバレッジレポート
3. パフォーマンス監視

### Phase 3: 高度な設定
1. 自動デプロイ設定
2. 監視・アラート設定
3. セキュリティスキャン

## 関連Issue

- Issue #58: GitHub Actionsビルドエラー修正 ✅ 完了
- Issue #52: テスト環境構築 - CI/CD連携予定
- Issue #55: Biome lintエラー修正 ✅ 完了

## 補足

CI/CD環境の整備により、Issue #52で構築予定のテスト環境との連携が可能になり、Issue #55で修正したlint設定の継続的な品質維持が実現される。
