### ISSUE TITLE
🔄 Documentation Sync: package.jsonとCLAUDE.mdの自動同期スクリプト

### ISSUE THREAD

**Issue by 24taro** [sotaroNishioka/notebooklm-collector#87]
## 🔄 Documentation Sync: package.jsonとCLAUDE.mdの自動同期スクリプト

**Type**: Enhancement
**Priority**: Low
**Effort**: S
**Impact**: Medium

### Current Issue
package.jsonに新しいスクリプトや依存関係が追加されても、CLAUDE.mdのドキュメントが手動で更新されるまで不整合が発生します。これにより：

- ドキュメントの信頼性低下
- 新機能の発見遅延
- 開発者の混乱

#### 自動同期スクリプトの作成
```typescript
// scripts/sync-docs.ts
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

interface PackageJson {
  scripts: Record<string, string>;
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
}

function syncDocsWithPackageJson() {
  // package.jsonの読み取り
  const packageJson: PackageJson = JSON.parse(
    readFileSync(join(__dirname, '../package.json'), 'utf-8')
  );

  // CLAUDE.mdの更新
  updateClaudeMd(packageJson);
  
  // README.mdの更新（必要に応じて）
  updateReadmeMd(packageJson);
}

function updateClaudeMd(packageJson: PackageJson) {
  // スクリプトセクションの生成
  const scriptsSection = generateScriptsSection(packageJson.scripts);
  
  // 技術スタックセクションの更新
  const techStackSection = generateTechStackSection(packageJson);
  
  // ファイルの更新
  // ...
}
```

#### GitHub Actionsワークフローの追加
```yaml
# .github/workflows/sync-docs.yml
name: Sync Documentation

on:
  push:
    paths:
      - 'package.json'
    branches:
      - main
      - 'feature/**'

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Run sync script
        run: npx tsx scripts/sync-docs.ts
      
      - name: Check for changes
        id: check-changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'docs: package.jsonとドキュメントの同期'
          body: 'package.jsonの変更を検出し、ドキュメントを自動更新しました。'
          branch: docs/sync-package-json
```

### Benefits
- **一貫性の保証**: package.jsonとドキュメントの常時同期
- **自動化**: 手動更新の負担削減
- **早期発見**: 不整合の即座の検出と修正
- **開発効率**: ドキュメント更新の手間削減

### Implementation Plan
1. 同期スクリプトの作成
2. テストの実装
3. GitHub Actionsワークフローの設定
4. 初回実行と検証
5. ドキュメントへの説明追加

### Acceptance Criteria
- [ ] package.json変更時に自動でPRが作成される
- [ ] スクリプトセクションが正確に同期される
- [ ] 依存関係の変更が反映される
- [ ] 手動での編集部分は保持される
- [ ] エラーハンドリングが適切に実装される

### Related Files
- `package.json` - 監視対象ファイル
- `CLAUDE.md` - 更新対象ファイル
- `README.md` - 更新対象ファイル（オプション）
- `scripts/sync-docs.ts` - 新規作成
- `.github/workflows/sync-docs.yml` - 新規作成

### 追加の考慮事項
- セクションの境界を明確にするためのマーカーコメント
- カスタマイズ可能な設定ファイル
- ドライラン機能の実装

---
🤖 **Auto-generated by Documentation Manager**
**Analysis Date**: 2025-01-06 07:35:00 UTC
